name: Run linter

on:
        - push

jobs:
        build:
                
                runs-on: ubuntu-latest
                steps:
                        - name: test code
                          run: make lint
